server:
  port: ${PORT:8080}

spring:
  application:
    name: pomodoro-app

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,https://pomodoro-frontend-eight.vercel.app}
    allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
    allowed-headers: ${CORS_ALLOWED_HEADERS:Authorization,Content-Type}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
